# Generated by Django 5.2.6 on 2025-09-13 15:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('agent_type', models.CharField(choices=[('gemini', 'Google Gemini'), ('gpt', 'OpenAI GPT'), ('claude', 'Anthropic Claude'), ('custom', 'Custom Agent')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('model_name', models.CharField(max_length=255)),
                ('system_prompt', models.TextField(default='You are a helpful AI assistant.')),
                ('capabilities', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
                ('max_concurrent_sessions', models.IntegerField(default=10)),
                ('rate_limit_per_minute', models.IntegerField(default=60)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='core.organization')),
                ('tags', models.ManyToManyField(blank=True, related_name='agents', to='core.tag')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organization', 'slug')},
            },
        ),
    ]
