# Generated by Django 6.0.2 on 2026-03-12 08:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pnu', models.CharField(blank=True, default='', max_length=19)),
                ('address', models.CharField(blank=True, default='', max_length=500)),
                ('site_polygon', models.JSONField(help_text='GeoJSON polygon of site boundary')),
                ('site_area_m2', models.FloatField(blank=True, null=True)),
                ('job_spec', models.JSONField(help_text='GA inputs/outputs/options spec')),
                ('constraints', models.JSONField(default=list, help_text='Auto-injected from land/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('generation_count', models.IntegerField(default=0)),
                ('max_generations', models.IntegerField(default=50)),
                ('population_size', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='design_opti_created_733c7c_idx'), models.Index(fields=['status'], name='design_opti_status_8135b6_idx')],
            },
        ),
        migrations.CreateModel(
            name='DesignResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.IntegerField()),
                ('design_id', models.IntegerField(help_text='Sequential ID within job')),
                ('inputs', models.JSONField(help_text='Design input parameters')),
                ('outputs', models.JSONField(default=dict, help_text='Evaluated metrics')),
                ('ranking', models.FloatField(blank=True, help_text='Pareto front number', null=True)),
                ('crowding_distance', models.FloatField(blank=True, null=True)),
                ('is_feasible', models.BooleanField(default=True)),
                ('is_pareto_optimal', models.BooleanField(default=False)),
                ('mass_geojson', models.JSONField(blank=True, help_text='3D mass GeoJSON for Cesium', null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='design.optimizationjob')),
            ],
            options={
                'ordering': ['job', 'generation', 'design_id'],
                'indexes': [models.Index(fields=['job', 'generation'], name='design_desi_job_id_4db516_idx'), models.Index(fields=['job', 'is_pareto_optimal'], name='design_desi_job_id_ca6e53_idx')],
            },
        ),
    ]
