# Generated by Django 6.0.2 on 2026-02-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZoningRegulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(help_text='e.g. 제1종일반주거지역', max_length=50, unique=True)),
                ('bcr_default', models.FloatField(help_text='Building Coverage Ratio %')),
                ('far_default', models.FloatField(help_text='Floor Area Ratio %')),
                ('bcr_article', models.CharField(blank=True, default='', help_text='e.g. 제77조', max_length=100)),
                ('far_article', models.CharField(blank=True, default='', help_text='e.g. 제78조', max_length=100)),
                ('restriction_keywords', models.JSONField(default=list, help_text='Keywords for law search')),
            ],
            options={
                'ordering': ['zone_name'],
            },
        ),
        migrations.CreateModel(
            name='LandQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.CharField(choices=[('pnu', 'PNU Code'), ('address', 'Address'), ('raw', 'Raw Data')], max_length=10)),
                ('raw_input', models.CharField(max_length=500)),
                ('resolved_pnu', models.CharField(blank=True, default='', max_length=19)),
                ('resolved_address', models.CharField(blank=True, default='', max_length=500)),
                ('zoning_zones', models.JSONField(default=list, help_text='List of zoning zone names')),
                ('building_coverage_limit', models.FloatField(blank=True, help_text='BCR %', null=True)),
                ('floor_area_limit', models.FloatField(blank=True, help_text='FAR %', null=True)),
                ('land_area_m2', models.FloatField(blank=True, null=True)),
                ('official_land_price', models.IntegerField(blank=True, help_text='Won/m2', null=True)),
                ('law_article_count', models.IntegerField(default=0)),
                ('response_time_ms', models.FloatField(default=0)),
                ('source', models.CharField(default='api', help_text='api | mcp | frontend', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='land_landqu_created_c653f1_idx'), models.Index(fields=['resolved_pnu'], name='land_landqu_resolve_305e46_idx')],
            },
        ),
    ]
