# Generated by Django 6.0.2 on 2026-02-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0002_landanalysisresult_landquery_analysis_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='landanalysisresult',
            name='land_use_situation',
            field=models.CharField(blank=True, default='', help_text='지목', max_length=50),
        ),
    ]
