# Generated by Django 6.0.2 on 2026-02-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0003_landanalysisresult_land_use_situation'),
    ]

    operations = [
        migrations.AddField(
            model_name='landanalysisresult',
            name='regulations_extended',
            field=models.JSONField(blank=True, default=dict, help_text='Items 11-41: zone/scale/text regulations'),
        ),
    ]
