# Generated by Django 6.0.2 on 2026-03-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0004_add_regulations_extended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landanalysisresult',
            name='corner_cutoff_required',
            field=models.BooleanField(default=False),
        ),
    ]
